from __future__ import annotations

try:
    import torch as _torch  # noqa: F401
except ImportError as exc:  # pragma: no cover - exercised only when torch is absent
    raise ImportError(
        "ml_pipes.torch requires the optional torch extra. Install it with `pip install ml-pipes[torch]`."
    ) from exc

from .ops import (
    TorchArgMax,
    TorchApplyTensorMask,
    TorchBinarizeTensor,
    TorchCreateTensorMask,
    TorchCreateTensorMaskByThreshold,
    TorchBinarizeTensorByThreshold,
    TorchFilterTensorsByMasksArea,
    TorchFilterTensorsByScore,
    TorchGatherRows,
    TorchGatherScores,
    TorchSelectTensors,
    TorchSigmoid,
    TorchSlice,
    TorchSortTensorsBy,
    TorchSoftmax,
    TorchTopK,
    TorchTopKIndices2D,
    ToDevice,
    ToNumpy,
    ToNumpyRegistry,
    ToTorch,
    ToTorchRegistry,
    TorchSynchronizeTensors,
    TorchAsType,
    TorchCollate,
    TorchDistribute,
    TorchExtract,
    TorchInfer,
    TorchMultiplyTensors,
    TorchMeanMaskScores,
    TorchMasksToBoxes,
    TorchNMS,
    TorchResizeMasks,
    TorchWeightMasksByScores,
)
from .types import TorchRuntimeOutputs, TorchTensorPayload, TorchTensorRegistry

__all__ = [
    "ToDevice",
    "TorchArgMax",
    "TorchApplyTensorMask",
    "TorchBinarizeTensor",
    "TorchCreateTensorMask",
    "TorchCreateTensorMaskByThreshold",
    "TorchBinarizeTensorByThreshold",
    "TorchFilterTensorsByMasksArea",
    "TorchFilterTensorsByScore",
    "TorchGatherRows",
    "TorchGatherScores",
    "TorchSelectTensors",
    "TorchSigmoid",
    "TorchSlice",
    "TorchSortTensorsBy",
    "TorchSoftmax",
    "TorchTopK",
    "TorchTopKIndices2D",
    "ToNumpy",
    "ToNumpyRegistry",
    "ToTorch",
    "ToTorchRegistry",
    "TorchSynchronizeTensors",
    "TorchAsType",
    "TorchCollate",
    "TorchDistribute",
    "TorchExtract",
    "TorchInfer",
    "TorchMultiplyTensors",
    "TorchMeanMaskScores",
    "TorchMasksToBoxes",
    "TorchNMS",
    "TorchResizeMasks",
    "TorchWeightMasksByScores",
    "TorchRuntimeOutputs",
    "TorchTensorPayload",
    "TorchTensorRegistry",
]
