from __future__ import annotations

from importlib import import_module
from typing import TYPE_CHECKING

__all__ = [
    "Benchmark",
    "BenchmarkBuilder",
    "BenchmarkCollector",
    "BenchmarkDiff",
    "BenchmarkSweep",
    "BenchmarkResult",
    "InvocationStat",
    "InvocationStatDiff",
    "MeasurementConfig",
    "data_factory",
    "pipeline_factory",
    "Factory",
    "PipelineFactory",
    "DataFactory",
    "InputFn",
    "SHORT_CIRCUIT",
    "ArgMax",
    "AggregateCollector",
    "CaptureCollector",
    "ConcurrentCollector",
    "InvocationTrace",
    "PrintCollector",
    "SerialCollector",
    "ThroughputCollector",
    "StepSpan",
    "TraceCollector",
    "TracingConfig",
    "Batch",
    "AsType",
    "Collate",
    "ConvertBoxFormat",
    "ConvertColorSpace",
    "Context",
    "DensityPrediction",
    "ClampDensity",
    "SumDensity",
    "ToDensityPrediction",
    "DensityToHeatmap",
    "BlendImages",
    "CollectItems",
    "Distinct",
    "DistinctBy",
    "Decode",
    "Detections",
    "Distribute",
    "DropNull",
    "DrawBoxes",
    "DrawMasks",
    "ApplyTensorMask",
    "BinarizeTensor",
    "CreateTensorMask",
    "CreateTensorMaskByThreshold",
    "BinarizeTensorByThreshold",
    "FilterTensorsByClasses",
    "FilterTensorsByMasksArea",
    "Extract",
    "FilterPredictions",
    "FilterPredictionsByArea",
    "FilterPredictionsByClass",
    "FilterPredictionsByScore",
    "FilterTensors",
    "FilterTensorsByScore",
    "MapTensor",
    "MultiplyTensors",
    "MeanMaskScores",
    "MasksToBoxes",
    "Select",
    "SelectTensors",
    "SortTensorsBy",
    "ResizeMasks",
    "TopK",
    "TopKIndices2D",
    "Prediction",
    "Gather",
    "GatherRows",
    "GatherScores",
    "Filter",
    "FilterNotNull",
    "HtmlRenderer",
    "GroupBlock",
    "ImagePayload",
    "InspectionResult",
    "InspectionSerializer",
    "PlotRenderer",
    "ImageBlock",
    "OutputBlock",
    "PipelineInspector",
    "Renderer",
    "StepView",
    "TextBlock",
    "OperatorArgument",
    "OperatorDescription",
    "PipelineDescription",
    "Infer",
    "LoadFile",
    "LogDetections",
    "LazyPerItem",
    "PerItem",
    "Map",
    "MapNotNull",
    "MapValue",
    "MapPredictionsToObjects",
    "NMM",
    "Operator",
    "OperatorLike",
    "NMS",
    "Normalize",
    "Pick",
    "embed",
    "Embed",
    "Inline",
    "inline",
    "Pipeline",
    "PipelineValidationError",
    "TypeContract",
    "ProjectBoxes",
    "ProjectMasks",
    "ProjectRoIMasks",
    "ReconstructMasks",
    "Recall",
    "RegionCloser",
    "RegionOpener",
    "WrapMappingInObject",
    "Resize",
    "ResizeTransform",
    "RuntimeOutputs",
    "SaveImage",
    "Scale",
    "Scatter",
    "Segmentations",
    "SideEffectOp",
    "Stitch",
    "Sigmoid",
    "Slice",
    "Softmax",
    "Squeeze",
    "Store",
    "StreamItems",
    "Take",
    "TakeWhile",
    "TensorPayload",
    "TensorRegistry",
    "Tile",
    "TileRect",
    "ToDetections",
    "ToSegmentations",
    "Transpose",
    "UnBatch",
    "WeightMasksByScores",
]

_MODULE_EXPORTS = {
    ".benchmark": [
        "Benchmark",
        "BenchmarkBuilder",
        "BenchmarkCollector",
        "BenchmarkDiff",
        "BenchmarkSweep",
        "BenchmarkResult",
        "InvocationStat",
        "InvocationStatDiff",
        "MeasurementConfig",
    ],
    ".collectors": [
        "AggregateCollector",
        "CaptureCollector",
        "ConcurrentCollector",
        "PrintCollector",
        "SerialCollector",
        "ThroughputCollector",
    ],
    ".core": [
        "Context",
        "Pipeline",
        "PipelineDescription",
        "Embed",
        "RegionCloser",
        "RegionOpener",
        "SHORT_CIRCUIT",
        "embed",
        "Inline",
        "inline",
        "Operator",
        "OperatorLike",
    ],
    ".factory": [
        "DataFactory",
        "Factory",
        "PipelineFactory",
        "data_factory",
        "pipeline_factory",
        "InputFn",
    ],
    ".inspection": [
        "GroupBlock",
        "HtmlRenderer",
        "ImageBlock",
        "InspectionResult",
        "InspectionSerializer",
        "OutputBlock",
        "PipelineInspector",
        "PlotRenderer",
        "Renderer",
        "StepView",
        "TextBlock",
    ],
    ".onnx": [
        "Distribute",
        "Extract",
        "Infer",
        "RuntimeOutputs",
    ],
    ".operator": [
        "OperatorArgument",
        "OperatorDescription",
    ],
    ".standard": [
        "Batch",
        "CollectItems",
        "Distinct",
        "DistinctBy",
        "DropNull",
        "Filter",
        "FilterNotNull",
        "Gather",
        "LazyPerItem",
        "Map",
        "MapNotNull",
        "MapValue",
        "PerItem",
        "Pick",
        "Recall",
        "Scatter",
        "Select",
        "SideEffectOp",
        "Store",
        "StreamItems",
        "Take",
        "TakeWhile",
        "UnBatch",
        "WrapMappingInObject",
    ],
    ".tensor": [
        "ApplyTensorMask",
        "ArgMax",
        "AsType",
        "BinarizeTensor",
        "BinarizeTensorByThreshold",
        "Collate",
        "CreateTensorMask",
        "CreateTensorMaskByThreshold",
        "FilterTensors",
        "GatherRows",
        "GatherScores",
        "MapTensor",
        "MultiplyTensors",
        "Scale",
        "SelectTensors",
        "Sigmoid",
        "Slice",
        "Softmax",
        "SortTensorsBy",
        "Squeeze",
        "TensorPayload",
        "TensorRegistry",
        "TopK",
        "TopKIndices2D",
        "Transpose",
    ],
    ".tracing": [
        "InvocationTrace",
        "StepSpan",
        "TraceCollector",
        "TracingConfig",
    ],
    ".vision": [
        "BlendImages",
        "ClampDensity",
        "ConvertBoxFormat",
        "ConvertColorSpace",
        "Decode",
        "DensityPrediction",
        "DensityToHeatmap",
        "Detections",
        "DrawBoxes",
        "DrawMasks",
        "FilterPredictions",
        "FilterPredictionsByArea",
        "FilterPredictionsByClass",
        "FilterPredictionsByScore",
        "FilterTensorsByClasses",
        "FilterTensorsByMasksArea",
        "FilterTensorsByScore",
        "ImagePayload",
        "LoadFile",
        "LogDetections",
        "MapPredictionsToObjects",
        "MasksToBoxes",
        "MeanMaskScores",
        "NMM",
        "NMS",
        "Normalize",
        "Prediction",
        "ProjectBoxes",
        "ProjectMasks",
        "ProjectRoIMasks",
        "ReconstructMasks",
        "Resize",
        "ResizeMasks",
        "ResizeTransform",
        "SaveImage",
        "Segmentations",
        "Stitch",
        "SumDensity",
        "Tile",
        "TileRect",
        "ToDensityPrediction",
        "ToDetections",
        "ToSegmentations",
        "WeightMasksByScores",
    ],
    ".validation": [
        "PipelineValidationError",
        "TypeContract",
    ],
}

_ATTR_TO_MODULE = {
    name: module_name
    for module_name, names in _MODULE_EXPORTS.items()
    for name in names
}

if TYPE_CHECKING:
    from .benchmark import (
        Benchmark,
        BenchmarkBuilder,
        BenchmarkCollector,
        BenchmarkDiff,
        BenchmarkResult,
        BenchmarkSweep,
        InvocationStat,
        InvocationStatDiff,
        MeasurementConfig,
    )
    from .collectors import (
        AggregateCollector,
        CaptureCollector,
        ConcurrentCollector,
        PrintCollector,
        SerialCollector,
        ThroughputCollector,
    )
    from .core import (
        Context,
        Embed,
        Inline,
        Operator,
        OperatorLike,
        Pipeline,
        PipelineDescription,
        RegionCloser,
        RegionOpener,
        SHORT_CIRCUIT,
        embed,
        inline,
    )
    from .factory import DataFactory, Factory, InputFn, PipelineFactory, data_factory, pipeline_factory
    from .inspection import (
        GroupBlock,
        HtmlRenderer,
        ImageBlock,
        InspectionResult,
        InspectionSerializer,
        OutputBlock,
        PipelineInspector,
        PlotRenderer,
        Renderer,
        StepView,
        TextBlock,
    )
    from .onnx import Distribute, Extract, Infer, RuntimeOutputs
    from .operator import OperatorArgument, OperatorDescription
    from .standard import (
        Batch,
        CollectItems,
        Distinct,
        DistinctBy,
        DropNull,
        Filter,
        FilterNotNull,
        Gather,
        LazyPerItem,
        Map,
        MapNotNull,
        MapValue,
        PerItem,
        Pick,
        Recall,
        Scatter,
        Select,
        SideEffectOp,
        Store,
        StreamItems,
        Take,
        TakeWhile,
        UnBatch,
        WrapMappingInObject,
    )
    from .tensor import (
        ApplyTensorMask,
        ArgMax,
        AsType,
        BinarizeTensor,
        BinarizeTensorByThreshold,
        Collate,
        CreateTensorMask,
        CreateTensorMaskByThreshold,
        FilterTensors,
        GatherRows,
        GatherScores,
        MapTensor,
        MultiplyTensors,
        Scale,
        SelectTensors,
        Sigmoid,
        Slice,
        Softmax,
        SortTensorsBy,
        Squeeze,
        TensorPayload,
        TensorRegistry,
        TopK,
        TopKIndices2D,
        Transpose,
    )
    from .tracing import InvocationTrace, StepSpan, TraceCollector, TracingConfig
    from .validation import PipelineValidationError, TypeContract
    from .vision import (
        BlendImages,
        ClampDensity,
        ConvertBoxFormat,
        ConvertColorSpace,
        Decode,
        DensityPrediction,
        DensityToHeatmap,
        Detections,
        DrawBoxes,
        DrawMasks,
        FilterPredictions,
        FilterPredictionsByArea,
        FilterPredictionsByClass,
        FilterPredictionsByScore,
        FilterTensorsByClasses,
        FilterTensorsByMasksArea,
        FilterTensorsByScore,
        ImagePayload,
        LoadFile,
        LogDetections,
        MapPredictionsToObjects,
        MasksToBoxes,
        MeanMaskScores,
        NMM,
        NMS,
        Normalize,
        Prediction,
        ProjectBoxes,
        ProjectMasks,
        ProjectRoIMasks,
        ReconstructMasks,
        Resize,
        ResizeMasks,
        ResizeTransform,
        SaveImage,
        Segmentations,
        Stitch,
        SumDensity,
        Tile,
        TileRect,
        ToDensityPrediction,
        ToDetections,
        ToSegmentations,
        WeightMasksByScores,
    )


def __getattr__(name: str) -> object:
    try:
        module_name = _ATTR_TO_MODULE[name]
    except KeyError as exc:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}") from exc
    module = import_module(module_name, __name__)
    value = getattr(module, name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__))
