from __future__ import annotations

import ml_pipes.vision as vision


def test_vision_component_surface_is_curated() -> None:
    assert vision.__all__ == [
        "BlendImages",
        "ClampDensity",
        "ConvertBoxFormat",
        "ConvertColorSpace",
        "Decode",
        "DensityPrediction",
        "DensityToHeatmap",
        "Detections",
        "DrawBoxes",
        "DrawMasks",
        "FilterPredictions",
        "FilterPredictionsByArea",
        "FilterPredictionsByClass",
        "FilterPredictionsByScore",
        "FilterTensorsByClasses",
        "FilterTensorsByMasksArea",
        "FilterTensorsByScore",
        "ImagePayload",
        "LoadFile",
        "LogDetections",
        "MapPredictionsToObjects",
        "MasksToBoxes",
        "MeanMaskScores",
        "NMM",
        "NMS",
        "Normalize",
        "Prediction",
        "ProjectBoxes",
        "ProjectMasks",
        "ProjectRoIMasks",
        "ReconstructMasks",
        "Resize",
        "ResizeMasks",
        "ResizeTransform",
        "SaveImage",
        "Segmentations",
        "Stitch",
        "SumDensity",
        "Tile",
        "TileRect",
        "ToDensityPrediction",
        "ToDetections",
        "ToSegmentations",
        "WeightMasksByScores",
    ]
